version: '3.1'
services:

<<<<<<< HEAD
  hello: # stateless spring application
    image: hello-img
    build: .
=======
  hello:
    image: valentin2211/hello-img:${IMAGE_TAG}
>>>>>>> 744f14e2409d509e59bd4152f987f34d69d7cad5
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@mongo:27017/
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  mongo:
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  mongo-admin-ui:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
<<<<<<< HEAD
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
=======
>>>>>>> 744f14e2409d509e59bd4152f987f34d69d7cad5
